import mongoose from 'mongoose';

const tagSchema = new mongoose.Schema(
    {
        userId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
            index: true,
        },
        name: {
            type: String,
            required: true,
            trim: true,
            lowercase: true,
        },
        isAutoGenerated: {
            type: Boolean,
            default: false,
        },
        itemCount: {
            type: Number,
            default: 0,
        },
        isDeleted: {
            type: Boolean,
            default: false,
            index: true,
        },
        deletedAt: {
            type: Date,
            default: null,
            index: true,
        },
    },
    { timestamps: true }
);

// Compound index to ensure unique tags per user
tagSchema.index({ userId: 1, name: 1, isDeleted: 1 }, { unique: true, sparse: true });

const tagModel = mongoose.model('Tag', tagSchema);

export default tagModel;
