import mongoose from 'mongoose';
import { Queue } from 'bullmq';
import env from '../config/env.js';
import { logEvent } from '../config/logger.js';
import { getRedis } from '../config/redis.js';
import Item from '../models/item.model.js';
import Job from '../models/job.model.js';
import Tag from '../models/tag.model.js';
import { buildAiText, deriveMetadata } from './content.service.js';
import { generateEmbedding } from './openai.service.js';
import { generateDetailedSummary, generateSummary } from './summary.service.js';
import { generateImageDescription } from './image.service.js';
import { generateTags } from './tags.service.js';
import { extractContent } from './extraction.service.js';
import { upsertItemVector } from './qdrant.service.js';
import { clusterUserItems } from './cluster.service.js';

const RETRY_DELAY_MS = {
    1: 0,
    2: 30_000,
    3: 300_000,
};
const MAX_RETRY_ATTEMPTS = Number(process.env.AI_JOB_MAX_RETRY_ATTEMPTS || 3);

const NON_RETRYABLE_PREFIXES = [
    'unsupported_job_type',
    'empty_query',
    'query_embedding_generation_failed',
    'embedding_generation_failed',
    'summary_generation_failed',
    'image_description_generation_failed',
];

const NON_RETRYABLE_SUBSTRINGS = [
    'tag generation failed: 400',
    'status code 400',
    'fetch failed',
];

function isRetryableError(errorMessage) {
    const normalized = String(errorMessage || '').toLowerCase();
    const blockedByPrefix = NON_RETRYABLE_PREFIXES.some((prefix) => normalized.startsWith(prefix));
    if (blockedByPrefix) return false;

    return !NON_RETRYABLE_SUBSTRINGS.some((fragment) => normalized.includes(fragment));
}

const processingQueue = new Queue('ai-processing', {
    connection: getRedis(),
    prefix: env.queuePrefix,
    skipVersionCheck: true,
});

const dlqQueue = new Queue('ai-dlq', {
    connection: getRedis(),
    prefix: env.queuePrefix,
    skipVersionCheck: true,
});

function normalizeVectorDimension(values) {
    if (!Array.isArray(values)) return [];

    const targetSize = Number(env.qdrantVectorSize || 1024);
    const numeric = values.map((v) => Number(v) || 0);

    if (numeric.length === targetSize) return numeric;

    if (numeric.length > targetSize) {
        return numeric.slice(0, targetSize);
    }

    return [...numeric, ...new Array(targetSize - numeric.length).fill(0)];
}

function toObjectId(raw) {
    if (!raw) return null;
    const value = String(raw).trim();
    return mongoose.Types.ObjectId.isValid(value) ? new mongoose.Types.ObjectId(value) : null;
}

async function isTerminalOrOrphan(jobId) {
    const id = toObjectId(jobId);
    if (!id) return false;

    const doc = await Job.findById(id).select('status').lean();
    if (!doc) return true;
    return ['success', 'failed', 'skipped'].includes(String(doc.status || ''));
}

async function markJob(jobId, update) {
    const id = toObjectId(jobId);
    if (!id) return;
    await Job.findByIdAndUpdate(id, update);
}

async function getOrCreateTagIds(userId, names) {
    const ids = [];

    for (const name of names) {
        const normalized = String(name || '').trim().toLowerCase();
        if (!normalized) continue;

        const tag = await Tag.findOneAndUpdate(
            { userId, name: normalized, isDeleted: { $ne: true } },
            {
                $setOnInsert: {
                    userId,
                    name: normalized,
                    autoGenerated: true,
                    color: '#F97316',
                },
                $inc: { itemCount: 1 },
            },
            { new: true, upsert: true }
        );

        ids.push(tag._id);
    }

    return ids;
}

async function attachAutoTagSuggestions(item, aiText, itemId) {
    try {
        const autoTags = await generateTags(aiText);
        if (Array.isArray(autoTags) && autoTags.length > 0) {
            item.metadata = item.metadata || {};
            item.metadata.autoTags = [...new Set(autoTags.map((tag) => String(tag || '').trim()).filter(Boolean))];
            return item.metadata.autoTags;
        }
    } catch (error) {
        logEvent('warn', 'summary_auto_tags_skipped', {
            itemId: String(itemId),
            error: error.message,
        });
    }

    return [];
}

async function buildItemAnalysisText(item, aiText) {
    const imageUrl = String(item?.metadata?.imageUrl || item?.url || '').trim();

    if (item?.type !== 'image' || !imageUrl) {
        return {
            analysisText: aiText,
            imageDescription: '',
        };
    }

    try {
        const imageDescription = await generateImageDescription(imageUrl, {
            title: item?.title || '',
            description: item?.description || '',
            content: aiText,
        });

        return {
            analysisText: imageDescription || aiText,
            imageDescription,
        };
    } catch (error) {
        logEvent('warn', 'pipeline_image_description_skipped', {
            itemId: String(item?._id || ''),
            error: error.message,
        });

        return {
            analysisText: aiText,
            imageDescription: '',
        };
    }
}

async function processItemPipeline(userId, itemId, item, dbJobId) {
    const extracted = await extractContent(item);
    const baseText = extracted.cleanedText || extracted.content || buildAiText(item);
    const { analysisText, imageDescription } = await buildItemAnalysisText(item, baseText);

    if (!analysisText) {
        throw new Error('empty_content');
    }

    let summary = '';
    let detailedSummary = '';
    try {
        if (imageDescription) {
            summary = imageDescription;
            detailedSummary = imageDescription;
            item.imageDescription = imageDescription;
            item.detailedSummary = imageDescription;
        } else {
            summary = await generateSummary(analysisText);
        }

        if (summary) {
            item.summary = summary;
        }

        if (!imageDescription) {
            try {
                detailedSummary = await generateDetailedSummary(analysisText);
                if (detailedSummary) {
                    item.detailedSummary = detailedSummary;
                } else if (summary) {
                    item.detailedSummary = summary;
                }
            } catch {
                if (summary) {
                    item.detailedSummary = summary;
                }
            }
        }
    } catch (error) {
        logEvent('warn', 'pipeline_summarization_skipped', {
            itemId: String(itemId),
            error: error.message,
        });
    }

    let autoTags = [];
    try {
        autoTags = await generateTags(analysisText);
        if (autoTags && autoTags.length > 0) {
            const tagIds = await getOrCreateTagIds(userId, autoTags);
            item.metadata = item.metadata || {};
            item.metadata.autoTags = autoTags;
            item.tags = [...new Set([...(item.tags || []).map(String), ...tagIds.map(String)])];
        }
    } catch (error) {
        logEvent('warn', 'pipeline_tagging_skipped', {
            itemId: String(itemId),
            error: error.message,
        });
    }

    try {
        const rawVector = await generateEmbedding(analysisText);
        if (Array.isArray(rawVector) && rawVector.length > 0) {
            const vector = normalizeVectorDimension(rawVector);
            item.embeddings = vector;

            await upsertItemVector({
                userId,
                itemId,
                values: vector,
                metadata: deriveMetadata(item),
            });
        }
    } catch (error) {
        logEvent('warn', 'pipeline_embedding_skipped', {
            itemId: String(itemId),
            error: error.message,
        });
    }

    await item.save();

    logEvent('info', 'pipeline_process_item_completed', {
        itemId: String(itemId),
        hasSummary: Boolean(summary),
        hasDetailedSummary: Boolean(detailedSummary),
        tagCount: autoTags.length,
        hasEmbedding: item.embeddings?.length > 0,
    });
}

export async function processJob(queueJob) {
    const data = queueJob?.data || {};
    const attempt = Number(data.attempt || 1);
    const jobType = String(data.type || queueJob.name || '').trim();
    const userId = toObjectId(data.userId);
    const itemId = toObjectId(data.itemId);
    const dbJobId = String(data.jobId || '').trim();

    logEvent('info', 'job_started', {
        jobId: dbJobId || String(queueJob.id),
        userId: String(data.userId || ''),
        itemId: String(data.itemId || ''),
        attempt,
    });

    if (await isTerminalOrOrphan(dbJobId)) {
        logEvent('info', 'orphan_or_terminal_job_skipped', {
            jobId: dbJobId || String(queueJob.id),
            userId: String(data.userId || ''),
            itemId: String(data.itemId || ''),
            attempt,
        });
        return;
    }

    if (!userId || !itemId) {
        throw new Error('invalid_job_payload');
    }

    const item = await Item.findOne({ _id: itemId, userId, isDeleted: { $ne: true } });
    if (!item) {
        throw new Error('item_not_found');
    }

    if (jobType === 'cluster-items') {
        const clusterResult = await clusterUserItems(userId);

        await markJob(dbJobId, {
            $set: { status: 'success', lastError: null },
            $inc: { attempts: 1 },
        });

        logEvent('info', 'cluster_job_completed', {
            jobId: dbJobId || String(queueJob.id),
            userId: String(userId),
            itemId: String(itemId),
            clusterCount: Number(clusterResult?.clusterCount || 0),
            updatedCount: Number(clusterResult?.updatedCount || 0),
            mode: clusterResult?.reason || 'unknown',
        });
        return;
    }

    const aiText = buildAiText(item);
    const { analysisText, imageDescription } = await buildItemAnalysisText(item, aiText);

    if (!analysisText) {
        throw new Error('empty_content');
    }

    // Handle unified process-item type
    if (jobType === 'process-item') {
        await processItemPipeline(userId, itemId, item, dbJobId);
    }
    // Handle legacy job types for backward compatibility
    else if (jobType === 'summarize-item') {
        if (imageDescription) {
            item.imageDescription = imageDescription;
            item.summary = imageDescription;
            item.detailedSummary = imageDescription;
        } else {
            const summary = await generateSummary(analysisText);
            if (!summary) throw new Error('summary_generation_failed');

            item.summary = summary;

            try {
                const detailedSummary = await generateDetailedSummary(analysisText);
                item.detailedSummary = detailedSummary || summary;
            } catch {
                item.detailedSummary = summary;
            }
        }

        await attachAutoTagSuggestions(item, analysisText, itemId);

        await item.save();
    } else if (jobType === 'tag-item') {
        const tags = await generateTags(analysisText);
        const tagIds = await getOrCreateTagIds(userId, tags);

        item.metadata = item.metadata || {};
        item.metadata.autoTags = tags;
        item.tags = [...new Set([...(item.tags || []).map(String), ...tagIds.map(String)])];
        await item.save();
    } else if (jobType === 'embed-item') {
        const rawVector = await generateEmbedding(analysisText);
        if (!Array.isArray(rawVector) || rawVector.length === 0) {
            throw new Error('embedding_generation_failed');
        }

        const vector = normalizeVectorDimension(rawVector);

        item.embeddings = vector;
        await item.save();

        await upsertItemVector({
            userId,
            itemId,
            values: vector,
            metadata: deriveMetadata(item),
        });
    } else if (jobType === 'embed-query') {
        const rawVector = await generateEmbedding(String(data.query || ''));
        if (!Array.isArray(rawVector) || rawVector.length === 0) {
            throw new Error('query_embedding_generation_failed');
        }

        const vector = normalizeVectorDimension(rawVector);

        const redis = getRedis();
        if (data.cacheKey) {
            await redis.set(String(data.cacheKey), JSON.stringify(vector), 'EX', 3600);
        }
    } else {
        throw new Error(`unsupported_job_type:${jobType}`);
    }

    await markJob(dbJobId, {
        $set: { status: 'success', lastError: null },
        $inc: { attempts: 1 },
    });

    const pending = await Job.countDocuments({ itemId, status: 'pending' });
    if (pending === 0) {
        await Item.updateOne({ _id: itemId, userId }, { $set: { status: 'processed', processingError: null } });
    }

    logEvent('info', 'job_success', {
        jobId: dbJobId || String(queueJob.id),
        userId: String(userId),
        itemId: String(itemId),
        type: jobType,
    });
}

export async function handleJobFailure(queueJob, error) {
    const data = queueJob?.data || {};
    const attempt = Number(data.attempt || 1);
    const nextAttempt = attempt + 1;
    const dbJobId = String(data.jobId || '').trim();
    const userId = toObjectId(data.userId);
    const itemId = toObjectId(data.itemId);
    const errorMessage = String(error?.message || error || 'job_failed');

    const isRetryable = isRetryableError(errorMessage);

    if (dbJobId) {
        await markJob(dbJobId, {
            $set: { lastError: errorMessage },
            $inc: { attempts: 1 },
            $push: { errorLogs: errorMessage },
        });
    }

    if (nextAttempt <= MAX_RETRY_ATTEMPTS && isRetryable) {
        await processingQueue.add(
            String(data.type || queueJob.name),
            { ...data, attempt: nextAttempt },
            {
                delay: RETRY_DELAY_MS[nextAttempt] || 0,
                removeOnComplete: 500,
                removeOnFail: 500,
            }
        );

        logEvent('info', 'job_retry_scheduled', {
            jobId: dbJobId || String(queueJob.id),
            attempt: nextAttempt,
            errorMessage,
        });

        return;
    }

    if (dbJobId) {
        await markJob(dbJobId, { $set: { status: 'failed', lastError: errorMessage } });
    }

    if (userId && itemId) {
        await Item.updateOne(
            { _id: itemId, userId },
            { $set: { status: 'processed_without_ai', processingError: errorMessage } }
        );
    }

    await dlqQueue.add(
        'dlq-event',
        {
            ...data,
            error: errorMessage,
            failedAt: new Date().toISOString(),
        },
        {
            removeOnComplete: 500,
            removeOnFail: 500,
        }
    );

    logEvent('error', 'job_failed_and_dlq', {
        jobId: dbJobId || String(queueJob.id),
        errorMessage,
        attempt,
    });
}
