import mongoose from 'mongoose';

const tagSchema = new mongoose.Schema(
    {
        userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
        name: { type: String, required: true, trim: true },
        color: { type: String, default: '#3B82F6', trim: true },
        itemCount: { type: Number, default: 0 },
        autoGenerated: { type: Boolean, default: false },
        isDeleted: { type: Boolean, default: false, index: true },
    },
    { timestamps: true }
);

tagSchema.index({ userId: 1, name: 1 }, { unique: true });

export default mongoose.models.Tag || mongoose.model('Tag', tagSchema);
